Repository eclipse/xtext-core, pull requests merged in 2018-11, with the labels that each got.

#934 [eclipse/xtext#1182] fixed tests with java 11 agains java 8 target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.tests/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
Labels: releng

#952 [#893] build against LSP4J 0.6.0-SNAPSHOT
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: releng

#954 [#893] build agains lsp4j snapshots
  gradle/versions.gradle
  releng/pom.xml
Labels: releng

#960 [#959] hasAnnotation: Add null guard
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Labels: bug

#963 [eclipse/xtext#1168] Minimal target platform Oxygen.3a
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#964 [eclipse/xtext-eclipse#900] Use org.eclipse.xtend.typesystem.emf 2.2.0
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: bug, releng

#955 [#893] switch to lsp4j 0.6.0 final
  gradle/versions.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: releng
