Repository eclipse/xtext-core, pull requests merged in 2018-03, with the labels that each got.

#651 startsWith: return false for null argument
  org.eclipse.xtext.tests/src/org/eclipse/xtext/naming/QualifiedNameTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java
Labels: enhancement

#662 [#476] Support EMF's ResourceLocators in XtextResourceSet.
  org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/XtextResourceSetTest.xtend
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractResourceSetTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractXtextResourceSetTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/NullResource.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/ResourceSetTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/SynchronizedXtextResourceSetTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/XtextResourceSetTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java
Labels: enhancement

#660 Add Code Mining support
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.java
Labels: new_feature

#667 [eclipse/xtext-eclipse#520] Adjust to latest API
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.java
Labels: refactoring
