Repository eclipse/xtext-core, pull requests merged in 2018-09, with the labels that each got.

#855 updated versions to 2.16.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng

#866 [eclipse/xtext#1297] update to gradle 4.10 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.jar
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew
Labels: releng

#865 [eclipse/xtext#1297] update to gradle 4.10
  gradle/wrapper/gradle-wrapper.properties
Labels: releng

#871 Removed copied code from Strings.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/StringsTest.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java
Labels: enhancement

#872 Fixed another location with duplicated code
  org.eclipse.xtext/src/org/eclipse/xtext/conversion/impl/STRINGValueConverter.java
Labels: enhancement

#757 [eclipse/xtext#1224] Detect local Jenkins environment
  Jenkinsfile
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/pom.xml
Labels: releng

#878 [eclipse/xtext#1272] Compile with Xtend 2.15
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ColoringTest.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/SignatureHelpTest.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/coloring/ColoringServiceImpl.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/editor/syntaxcoloring/SemanticHighlightingCalculatorImpl.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/signatureHelp/SignatureHelpServiceImpl.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/TestLanguageValidator.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/ContentAssistEntry.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IdeCrossrefProposalProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyRoot.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/syntaxcoloring/DefaultAntlrTokenToAttributeIdMapper.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/syntaxcoloring/HighlightingStyles.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/IImageDescription.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerExtension.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ServerLauncher.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/hover/IHoverService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.java
  org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/logging/LoggingTester.java
  org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/util/InMemoryURIHandler.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/filesystem/URIBasedFileSystemAccessTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/SerializerPerformanceTest.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/AbstractGeneratorFragmentTests.java
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/CodeConfig.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorStandaloneSetup.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/FragmentFakingEcoreResource.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/GuiceModuleAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/JavaFileAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/ManifestAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/PluginXmlAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/XtendFileAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/util/GrammarUtil2.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/BuildRequest.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/Indexer.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TracedAccessorsProcessor.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/PortableURIs.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/StorageAwareResource.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.java
Labels: codegen

#877 Testing more methods from JavaVersion
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/JavaVersionTest.java
Labels: test
