Repository eclipse/xtext-core, pull requests merged in 2018-04, with the labels that each got.

#670 [#666] JUnit 5 support
  gradle/versions.gradle
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/build.gradle
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/AbstractJUnitIntegrationTest.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/InjectionExtensionTest.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/XtextRunnerTest.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/JUnitVersion.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WizardConfiguration.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WizardConfiguration.java
Labels: new_feature

#711 [eclipse/xtext#1190] Narrowed the version range for asm to [6.1.1,6.2.0)
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#633 [refactoring] Deprecate methods with correspondence in Guava
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/Files.java
Labels: refactoring

#719 [#714] consume lsp4j 0.4.0 final
  gradle/versions.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: releng
