Repository eclipse/xtext-core, pull requests merged in 2019-09, with the labels that each got.

#1235 [releng] Set version to 2.20.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng

#1234 [eclipse/xtext#1520] update to gradle 5.6.1
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  org.eclipse.xtext.ide.tests/.classpath
  org.eclipse.xtext.testing/.classpath
  org.eclipse.xtext.tests/.classpath
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew
Labels: releng

#1240 [eclipse/xtext#1547] use maven-publish instead of maven plugin
  1-gradle-build.sh
  build.gradle
  gradle/developers.gradle
  gradle/maven-deployment.gradle
Labels: releng

#1243 [eclipse/xtext#1538] use eclipse 2019-12 in target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#1246 [https://github.com/eclipse/xtext/issues/1486]
  org.eclipse.xtext/about.ini
  org.eclipse.xtext/xtext32.png
Labels: enhancement

#1247 [https://github.com/eclipse/xtext/issues/1486]
  org.eclipse.xtext/build.gradle
Labels: enhancement

#1249 fixed settings.xml config in Jenkinsfile
  Jenkinsfile
Labels: releng

#1248 [https://github.com/eclipse/xtext/issues/1486]
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar.ide/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
  org.eclipse.xtext/build.gradle
  org.eclipse.xtext/modeling32.png
Labels: refactoring
