Repository eclipse/xtext-core, pull requests merged in 2019-04, with the labels that each got.

#1102 Update to Gradle 5.3.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew.bat
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.jar
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew.bat
Labels: releng

#1104 [eclipse/xtext#1424] Change default Jenkins
  README.md
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  releng/pom.xml
Labels: releng

#1107 Use mavenCentral instead of jcenter to avoid sync delays and stability issues
  build.gradle
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  releng/pom.xml
Labels: releng

#1109 [#1076] Remove BOM managed versions
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: enhancement

#1111 [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI
  1-gradle-build.sh
  2-maven-build.sh
  CBI.Jenkinsfile
  releng/pom.xml
Labels: releng

#1112 [xtext-xtend#734] Fixed restore logic of runtime injector providers
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/IndentationAwareUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/PartialContentAssistTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/PartialSerializationTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/RenameTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/TestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentHighlightTest2.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/fileAware/tests/FileAwareTestLanguageInjectorProvider.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/tests/XtextGrammarTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/formatting2/internal/tests/FormatterTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/formatting2/regionaccess/internal/tests/RegionAccessTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/tests/LazyLinkingTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/fragments/tests/FragmentTestLanguageExInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/fragments/tests/FragmentTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/indentation/tests/IndentationAwareTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/NoParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/ParametersTestLanguageExInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/ParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/TwoParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parsetree/reconstr/serializer/SerializationErrorTestLanguageSemanticSequencer.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/tests/SequencerTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/XtextInjectorProvider.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java
Labels: bug

#1110 [eclipse/xtext#1403] Improve progress monitor utilization
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java
Labels: enhancement

#1114 [#403] Fixed regression in injector provider
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/IndentationAwareUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/PartialContentAssistTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/PartialSerializationTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/RenameTestLanguageInjectorProvider.java
  org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/tests/TestLanguageInjectorProvider.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/fileAware/tests/FileAwareTestLanguageInjectorProvider.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/tests/XtextGrammarTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/formatting2/internal/tests/FormatterTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/formatting2/regionaccess/internal/tests/RegionAccessTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/lazy/tests/LazyLinkingTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/fragments/tests/FragmentTestLanguageExInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/fragments/tests/FragmentTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/indentation/tests/IndentationAwareTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/NoParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/ParametersTestLanguageExInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/ParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/parameters/tests/TwoParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/tests/SequencerTestLanguageInjectorProvider.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/XtextInjectorProvider.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java
Labels: bug

#1115 [eclipse/xtext#1422] update to tycho 1.4.0
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.tests/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
  releng/pom.xml
Labels: releng

#1118 use https
  releng/releng-target/xtext-core.target.target
Labels: releng

#1129 [eclipse/xtext#1434] Explicit agent configuration
  CBI.Jenkinsfile
Labels: releng

#1133 [refactoring] a bit of progress monitor rework in `ChangeSerializer`
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java
Labels: enhancement

#1134 [refactoring] introduced default method in 'IResourceRelocationStrategy' allowing to switch to persisted index
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.xtend
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.java
Labels: enhancement, refactoring
