Repository eclipse/xtext-core, pull requests merged in 2019-02, with the labels that each got.

#1012 set minimal mwe version to the one from oxygen
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#1013 bump grgit
  build.gradle
Labels: releng

#1014 Fix ui tests
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
Labels: bug

#984 [#983] Make issue message customizable
  org.eclipse.xtext/src/org/eclipse/xtext/validation/CompositeEValidator.java
Labels: enhancement

#1015 [eclipse/xtext#1391] pin guava version to 21
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
Labels: releng

#1016 Set sourceEncoding ISO-8859-1
  releng/pom.xml
Labels: releng

#986 [#985] Make swallowing of NPEs in validation code configurable
  org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/DeclarativeValidatorTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java
Labels: enhancement

#1023 [eclipse/xtext#1394] bootstrap against 2.17.0.M2
  gradle/versions.gradle
Labels: releng

#1024 Make bin/main also the default output directory to avoid buildship confusion
  gradle/eclipse-project-layout.gradle
  org.eclipse.xtext.ide.tests/.classpath
  org.eclipse.xtext.ide/.classpath
  org.eclipse.xtext.testing/.classpath
  org.eclipse.xtext.testlanguages.ide/.classpath
  org.eclipse.xtext.testlanguages/.classpath
  org.eclipse.xtext.tests/.classpath
  org.eclipse.xtext.util/.classpath
  org.eclipse.xtext.xtext.generator/.classpath
  org.eclipse.xtext.xtext.ide/.classpath
  org.eclipse.xtext.xtext.wizard/.classpath
  org.eclipse.xtext/.classpath
Labels: releng

#1031 isAssignableFrom: check both args for null & identity
  org.eclipse.xtext.tests/src/org/eclipse/xtext/EcoreUtil2Test.java
  org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java
Labels: enhancement

#1030 [performance] Improve isInstantiatableSubType
  org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinker.java
Labels: enhancement, performance

#1028 [eclipse/xtext#1283] switched to MWE 2.10 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1036 workaround for jcenter maven central sync is too slow
  gradle/upstream-repositories.gradle
Labels: releng

#1042 [eclipse/xtext#1283] Remove mavenCentral again
  gradle/upstream-repositories.gradle
Labels: releng

#1041 [#1034] Added Validation that entry rule is not a fragment
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ValidationIssue1034Test.xtend
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ValidationIssue1034Test.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Labels: new_feature

#1008 Make ResourceDescriptionStrategyFragment aware of super grammars
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/index/ResourceDescriptionStrategyFragment.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/index/ResourceDescriptionStrategyFragment.java
Labels: bug, confirmed

#1046 Actually delete LSP test folder after test
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend
Labels: bug

#1049 Added missing generated code + Fix for failing test due missing cleanup
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/WorkspaceManagerTest.xtend
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/WorkspaceManagerTest.java
  org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Labels: test
