Repository eclipse/xtext-core, pull requests merged in 2019-12, with the labels that each got.

#1311 [releng] Update Xtext version to 2.21.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: bot, releng

#1315 [releng] Bootstrap against 2.20.0
  gradle/versions.gradle
Labels: bot, releng

#1325 [#1324] teach partial class extractor about fragment rules
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/PartialClassExtractorTest.xtend
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/PartialClassExtractorTest.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/splitting/PartialClassExtractor.java
Labels: bug

#1322 Log Exceptions thrown in futures created by the RequestManger
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/AbstractRequest.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/ReadRequest.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java
  org.eclipse.xtext/src/org/eclipse/xtext/service/OperationCanceledManager.java
Labels: enhancement

#1327 [eclipse/xtext#1629] Migrate server.concurrent from Xtend to Java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/AbstractRequest.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/Cancellable.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/Cancellable.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/ReadRequest.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/AbstractRequest.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/ReadRequest.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java
Labels: refactoring
