Repository eclipse/xtext-core, pull requests merged in 2019-10, with the labels that each got.

#1254 [eclipse/xtext#1538] use orbit 2019-12
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1242 #1120 Fix merger in case of line breaks inside identifiers.
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
Labels: bug

#1258 [eclipse/xtext#1560] bootstrap against 2.20.0.M1
  gradle/versions.gradle
Labels: releng

#1260 [eclipse/xtext#1561] removed superfluous timestamps() config
  Jenkinsfile
Labels: releng

#1261 [eclipse/xtext#1553] update to tycho 1.5.0
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  releng/pom.xml
Labels: releng

#1263 [eclipse/xtext#1567] Upgrade to asm 7.2
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#1266 [eclipse/xtext#1566] update to tycho 1.5.1
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  releng/pom.xml
Labels: releng

#1267 [eclipse/xtext#1569] Refactor Xtend to Java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileProjectConfig.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileProjectConfig.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileSourceFolder.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/IProjectConfig.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/IWorkspaceConfig.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/ProjectConfigAdapter.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/ProjectConfigAdapter.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/ProjectConfigProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/ProjectConfigProvider.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/UnknownProjectConfig.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/WorkspaceConfig.java
  org.eclipse.xtext/src/org/eclipse/xtext/workspace/WorkspaceConfig.xtend
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/FileProjectConfig.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/FileSourceFolder.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/ProjectConfigAdapter.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/ProjectConfigProvider.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/UnknownProjectConfig.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/WorkspaceConfig.java
Labels: refactoring

#1270 [eclipse/xtext#1569] Migrate Xtend code to Java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/DefaultProjectDescriptionFactory.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerShutdownAndExitHandler.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/IProjectDescriptionFactory.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/IWorkspaceConfigFactory.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/IWorkspaceConfigFactory.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/MultiProjectWorkspaceConfigFactory.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/MultiProjectWorkspaceConfigFactory.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectWorkspaceConfigFactory.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/findReferences/WorkspaceResourceAccess.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/findReferences/WorkspaceResourceAccess.xtend
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService2.xtend
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/DefaultProjectDescriptionFactory.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/MultiProjectWorkspaceConfigFactory.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ProjectManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ProjectWorkspaceConfigFactory.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/findReferences/WorkspaceResourceAccess.java
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/builder/AbstractIncrementalBuilderTest.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/BufferedCancelIndicator.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/BuildContext.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/BuildContext.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/BuildRequest.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/BuildRequest.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/IndexState.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/IndexState.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/build/Source2GeneratedMapping.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/Source2GeneratedMapping.xtend
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/BuildContext.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/BuildRequest.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IncrementalBuilder.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IndexState.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/Indexer.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/Source2GeneratedMapping.java
Labels: refactoring
