Repository eclipse/xtext-core, pull requests merged in 2019-11, with the labels that each got.

#1269 [eclipse/xtext#1569] Refactor Xtend to Java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskFinder.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskFinder.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskTagProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskTagProvider.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/Task.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/Task.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/TaskTag.java
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/TaskTag.xtend
  org.eclipse.xtext/src/org/eclipse/xtext/tasks/TaskTags.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskFinder.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParser.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskTagProvider.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/Task.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/TaskTag.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/TaskTags.java
Labels: refactoring

#1273 [eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder
  gradle/eclipse-project-layout.gradle
  org.eclipse.xtext.ide.tests/.project
  org.eclipse.xtext.ide/.project
  org.eclipse.xtext.testing/.project
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/.project
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/.project
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/.project
  org.eclipse.xtext.util/.project
  org.eclipse.xtext.xtext.generator/.project
  org.eclipse.xtext.xtext.ide/.project
  org.eclipse.xtext.xtext.wizard/.project
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/.project
Labels: releng

#1279 [releng] Bootstrap against 2.20.0.M2
  gradle/versions.gradle
Labels: bot, releng

#1286 updated jetty to latest release
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
Labels: releng

#1290 log deprecation warning if xtend based postprocessor is used
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/XtendXtext2EcorePostProcessor.java
Labels: releng

#1293 cleanup versions.gradle
  gradle/versions.gradle
Labels: releng

#1295 updated grgit gradle plugin to version 4.0.0
  build.gradle
Labels: releng

#1280 [eclipse/xtext#1573] Provide proper build.properties
  org.eclipse.xtext.ide.tests/build.properties
  org.eclipse.xtext.ide.tests/plugin.properties
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/build.properties
  org.eclipse.xtext.ide/plugin.properties
  org.eclipse.xtext.testing/build.properties
  org.eclipse.xtext.testlanguages.ide/build.properties
  org.eclipse.xtext.testlanguages/build.properties
  org.eclipse.xtext.tests/build.properties
  org.eclipse.xtext.util/build.properties
  org.eclipse.xtext.xtext.generator/build.properties
  org.eclipse.xtext.xtext.ide/build.properties
  org.eclipse.xtext.xtext.wizard/build.properties
  org.eclipse.xtext/.cvsignore
  org.eclipse.xtext/META-INF/MANIFEST.MF
  org.eclipse.xtext/build.properties
  org.eclipse.xtext/plugin.properties
Labels: releng

#1297 [eclipse/xtext#1609] update to mwe 2.11.1
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1298 [eclipse/xtext#1569] Refactor Xtend to Java
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/DisposableRegistry.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/DisposableRegistry.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/IDisposable.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/IDisposable.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/IFileSystemScanner.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/IFileSystemScanner.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/LineAndColumn.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/LineAndColumn.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/internal/AlternateJdkLoader.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/internal/AlternateJdkLoader.xtend
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/DisposableRegistry.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/IFileSystemScanner.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/LineAndColumn.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/UriExtensions.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/internal/AlternateJdkLoader.java
Labels: refactoring

#1302 [releng] Bootstrap against 2.20.0.M3
  gradle/versions.gradle
Labels: bot, releng

#1305 Use mwe2version in POMs and target platform, instead of hard-coding
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: enhancement

#1310 Fix regression in XtextVersion.getCurrent()
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
Labels: regression
