Repository eclipse/xtext-core, pull requests merged in 2020-09, with the labels that each got.

#1534 [eclipse/xtext#1812] Use centos-7 pod template & config. JDK
  Jenkinsfile
Labels: releng

#1569 [#1568] Add restricted API to allow access to internals of the node model
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/InternalNodeModelUtils.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java
Labels: enhancement

#1571 [eclipse/xtext#1828] update orbit to 2020-12
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1572 [eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#1562 Improve performance of Xtext editor with large grammars
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/OverriddenValueInspector.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/PredicateUsesUnorderedGroupInspector.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextRuleInspector.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextScopeProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Labels: performance

#1574 use dev bom in tycho build
  releng/pom.xml
Labels: releng

#1567 [#1521] Return root on parse success and no other element found.
  org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/EObjectAtOffsetTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/EObjectAtOffsetHelper.java
Labels: bug

#1577 [eclipse/xtext#1851] More tests for the tests
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/AbstractJUnitIntegrationTest.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/XtextRunnerTest.java
  org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/junit5/InjectionExtensionTest.java
Labels: bug

#1580 [#1526] make new generator API
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
Labels: releng
