Repository eclipse/xtext-core, pull requests merged in 2020-01, with the labels that each got.

#1348 [eclipse/xtext#1642] regenerated xtend code with latest xtend
  org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/bracketmatching/IBracePairProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IIdeContentProposalAcceptor.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IPrefixMatcher.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/ICallHierarchyBuilder.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyBuilder.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyNode.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyNodeLocationProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyNodeReference.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/IHierarchyRoot.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/navigation/INavigatable.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/syntaxcoloring/HighlightingStyles.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/syntaxcoloring/IEditorHighlightingConfigurationProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/IImageDescription.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/IImageDescriptionProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/INameLabelProvider.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IRenameNameValidator.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IRenameStrategy2.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/RefactoringIssueAcceptor.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildListener.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ICapabilitiesContributor.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerAccess.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerExtension.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService2.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codelens/ICodeLensResolver.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codelens/ICodeLensService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/commands/IExecutableCommandService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/hover/IHoverService.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/IRenameService2.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/semanticHighlight/ISemanticHighlightingStyleToTokenMapper.java
  org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/IGuiceAwareGeneratorComponent.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/IXtextGeneratorFragment.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/Issues.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/IXtextGeneratorFileSystemAccess.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/annotations/IClassAnnotation.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/IBundleProjectConfig.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/IRuntimeProjectConfig.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/ISubProjectConfig.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/IWebProjectConfig.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/IXtextProjectConfig.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ProjectsCreator.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/IShouldGenerate.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/URIBasedFileSystemAccess.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/IResourceStorageFacade.java
  org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/SerializableEObjectDescriptionProvider.java
Labels: releng

#1354 [releng] Bootstrap against 2.21.0.M1
  gradle/versions.gradle
Labels: bot, releng

#1357 update grgit to 4.0.1
  build.gradle
Labels: releng

#1352 [#1351] match milestone versions in test too
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
Labels: bug

#1360 [eclipse/xtext#1643] update to tycho 1.6.0
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  releng/pom.xml
Labels: releng

#1361 [eclipse/xtext#1595] Escape branch name for k8s label
  Jenkinsfile
Labels: releng
