Repository eclipse/xtext-core, pull requests merged in 2020-08, with the labels that each got.

#1548 [releng] Bootstrap against 2.23.0.M2
  gradle/versions.gradle
Labels: bot, releng

#1549 API cleanup after Xtend2Java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageWritable.java
Labels: bug

#1547 removed obsolete org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.tests/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext/.settings/org.eclipse.xtend.shared.ui.prefs
Labels: releng

#1553 Improved grammar validation in the context of unassigned rule calls
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Labels: new_feature

#1552 Improved validation against imported ecore meta model
  org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parsetree/reconstr/serializer/SerializationErrorTestLanguageSemanticSequencer.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/multiinheritancetest.ecore
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfo.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfoAccess.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfos.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/ElementTypeCalculator.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreInterpretationContext.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
Labels: new_feature

#1554 fixed running workflows from gradle on windows
  gradle/mwe2-workflows.gradle
Labels: releng

#1558 [releng] Bootstrap against 2.23.0.M3
  gradle/versions.gradle
Labels: bot, releng

#1564 [releng] Update Xtext version to 2.24.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: bot, releng

#1565 [releng] Bootstrap against 2.23.0
  gradle/versions.gradle
Labels: bot, releng
