Repository eclipse/xtext-core, pull requests merged in 2020-05, with the labels that each got.

#1477 [releng] Bootstrap against 2.22.0.M2
  gradle/versions.gradle
Labels: bot, releng

#1480 [eclipse/xtext#1738] removed no longer needed icu dependency
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/build.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/build.properties
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/build.gradle
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
Labels: releng

#1481 marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend
  org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/XtextRuntimeModule.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextLinker.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/IXtext2EcorePostProcessor.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/XtendXtext2EcorePostProcessor.java
  org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
Labels: technical_debt

#1484 [eclipse/xtext#1765] update to MWE 2.11.3.M3
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1483 [#1466] Global unique name validator
  org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelperTest.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/NamesAreUniqueValidatorTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultResourceDescriptionManager.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/IsAffectedExtension.java
  org.eclipse.xtext/src/org/eclipse/xtext/service/DefaultRuntimeModule.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/DefaultUniqueNameContext.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/INamesAreUniqueValidationHelper.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/LocalUniqueNameContext.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidator.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/UniqueInResourceContext.java
Labels: new_feature

#1501 [eclipse/xtext#1770] update to mwe 2.11.3 final
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1500 [#1499] Enable JavaDoc validation on org.eclipse.xtext
  org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelperTest.java
  org.eclipse.xtext/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext/src/org/eclipse/xtext/naming/DefaultDeclarativeQualifiedNameProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/serializer/diagnostic/ISemanticSequencerDiagnosticProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/INamesAreUniqueValidationHelper.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java
Labels: releng

#1504 [releng] Bootstrap against 2.22.0.M3
  gradle/versions.gradle
Labels: bot, releng

#1505 [eclipse/xtext#1769] Removed jnlp image name from pod template
  Jenkinsfile
Labels: releng
