Repository eclipse/xtext-core, pull requests merged in 2020-06, with the labels that each got.

#1513 [releng] Update Xtext version to 2.23.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: bot, releng

#1528 [eclipse/xtext#1781] update orbit to 2020-09
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1527 [eclipse/xtext#1801] increase build timeout
  Jenkinsfile
Labels: releng

#1529 [eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#1533 [#1497] Don't clear the cache on bulk changes to errors or warnings
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/OnChangeEvictingCacheAdapterTest.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java
Labels: performance

#1537 [#1536] Make LazyLinkingResource#proxyInformation available to sub-types
  org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java
Labels: enhancement
