Repository eclipse/xtext-core, pull requests merged in 2021-01, with the labels that each got.

#1657 Consider Beta release pattern in version string
  org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
Labels: bug

#1658 [eclipse/xtext#1916] Upgrade GSON to 2.8.6
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: dependencies

#1651 [#1648] fixed regression in InjectionExtension
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java
  org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/fileAware/validation/FileAwareTestLanguageValidator.java
  org.eclipse.xtext.tests/build.gradle
  org.eclipse.xtext.tests/src/org/eclipse/xtext/junit5/RunSuiteJUnit5.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/junit5/FileAwareTestLanguageValidationJunit5Test.java
Labels: bug

#1660 [#1655] fixed k=x generation if k is set in parser options
  org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguage.g
  org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguageLexer.java
  org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguageParser.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguage.g
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguageLexer.java
  org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguageParser.java
  org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/noJdt/NoJdtTestLanguage.mwe2
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
Labels: bug

#1662 [releng] Bootstrap against 2.25.0.M1
  gradle/versions.gradle
Labels: bot, releng

#1667 [eclipse/xtext-core#1666] added testcase for special ML_COMMENT
  org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensions2Test.java
Labels: bug
