Repository eclipse/xtext-core, pull requests merged in 2021-05, with the labels that each got.

#1705 [#1703] Cleanup preferences API
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/BooleanKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/EnumKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/IPreferenceValues.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/IPreferenceValuesProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/ITypedPreferenceValues.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/IntegerKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/MapBasedPreferenceValues.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceKeysProvider.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceValuesByLanguage.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/StringKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/TypedPreferenceKey.java
  org.eclipse.xtext/src/org/eclipse/xtext/preferences/TypedPreferenceValues.java
Labels: enhancement

#1706 bumped exec-maven-plugin to 3.0.0 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/lsMavenApp/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
Labels: releng

#1708 [releng] Bootstrap against 2.26.0.M1
  gradle/versions.gradle
Labels: bot, releng
