Repository eclipse/xtext-core, pull requests merged in 2022-09, with the labels that each got.

#1961 [eclipse/xtext#2096] update to tycho 2.7.5
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Labels: releng

#1962 [eclipse/xtext#2097] remove java nature from project roots
  .classpath
  .project
  .settings/org.eclipse.jdt.core.prefs
  gradle/bootstrap-setup.gradle
Labels: releng

#1963 [eclipse/xtext#2092] update to 2022-12 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.target/mavenTychoP2J11.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#1965 [eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ide.tests/.settings/org.eclipse.jdt.core.prefs
Labels: releng

#1966 bump jetty to 9.4.49.v20220914
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
Labels: releng

#1967 [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
  NOTICE.md
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.target/mavenTychoP2J11.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#1975 [#1968] Improved handling of encoded URIs in UriExtensions
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsIntegrationTest.java
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.java
Labels: bug

#1978 [eclipse/xtext-extras#805] Enhance NoJdtTestLanguageGenerator
  org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/noJdt/generator/NoJdtTestLanguageGenerator.java
Labels: new_feature
