Repository eclipse/xtext-core, pull requests merged in 2022-11, with the labels that each got.

#1997 [eclipse/xtext#2106] Update to MWE 2.14.0.M1
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#2001 use fixed asm 9.4 version from orbit m3
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#2002 Rename private variable to follow public method name
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalAcceptor.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java
Labels: bug

#1995 [eclipse/xtext-core#1993] update to lsp4j 0.18.0
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
Labels: releng

#2006 [eclipse/xtext#2112] Fix Orbit signing problem
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#2009 make full use of Java 11 Deprecated annotation
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
  org.eclipse.xtext/src/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.java
Labels: releng

#2007 [eclipse/xtext#2112] switch back to orbit 2022-12 in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#2013 [releng] Bootstrap against 2.29.0.M3
  gradle/versions.gradle
Labels: releng, bot

#2008 [eclipse/xtext#2112] switch back to orbit 2022-12
  releng/releng-target/xtext-core.target.target
Labels: releng

#2017 [eclipse/xtext-core#2004] Update to lsp4j 0.19.0
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
Labels: releng

#2024 [releng] Update Xtext version to 2.30.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng, bot

#2026 bootstrap against 2.29 release
  releng/releng-target/xtext-core.target.target
Labels: releng

#2020 remove J8 support from wizard
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreatorMain.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.java
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#2011 [#2010] fix Java 18 Runtime.exec deprecation
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/GraphvizDotBuilder.java
Labels: releng
