Repository eclipse/xtext-core, pull requests merged in 2022-10, with the labels that each got.

#1980 Fixed logging in ResolvedResourceDescription
  org.eclipse.xtext/src/org/eclipse/xtext/build/ResolvedResourceDescription.java
Labels: bug

#1981 [releng] Bootstrap against 2.29.0.M1
  gradle/versions.gradle
Labels: releng, bot

#1982 bump tycho bootstrapping
  releng/releng-target/xtext-core.target.target
Labels: releng

#1979 [eclipse/xtext-core#1943] update to lsp4j 0.16.0
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
Labels: releng

#1992 [eclipse/xtext-core#1986]update to lsp4j 0.17.0
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
Labels: releng

#1991 [eclipse/xtext#2104] update to asm 9.4
  NOTICE.md
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#1994 [releng] Bootstrap against 2.29.0.M2
  gradle/versions.gradle
Labels: releng, bot
