Repository eclipse/xtext-core, pull requests merged in 2023-01, with the labels that each got.

#2046 [eclipse/xtext#2118] update to orbit 2023-03
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
  releng/releng-target/xtext-core.target.target
Labels: releng

#2049 [eclipse/xtext#2126] bump reload4j
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
  org.eclipse.xtext/META-INF/MANIFEST.MF
Labels: releng

#2050 [releng] Bootstrap against 2.30.0.M1
  gradle/versions.gradle
Labels: releng, bot

#2047 [eclipse/xtext#2079] update to gradle 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradlew.bat
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradlew
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradlew.bat
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.jar
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew.bat
Labels: releng

#2053 [eclipse/xtext#2134] remove dependency to obsolte jdt.compiler.(tool|apt)
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Labels: releng

#2059 [#2058] fix assertAllWhitespaceIsFormatted
  org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/formatter/FormatterTestHelper.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormatterTestLanguageJavaFormatter.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/JavaFormatterTest.java
Labels: bug

#2056 [#2055] fix newline at end of file
  org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/debug/TextRegionsWithTitleToStringTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/LineRegion.java
Labels: bug

#2062 [releng] Bootstrap against 2.30.0.M2
  gradle/versions.gradle
Labels: releng, bot
