Repository eclipse/xtext-core, pull requests merged in 2023-02, with the labels that each got.

#2064 update to tycho 3.0.2
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Labels: releng

#2067 bumped some maven plugins in wizard
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: releng

#2066 [eclipse/xtext-core#2019] update to lsp4j 0.20.0
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
Labels: releng

#2048 [eclipse/xtext#2131] update to gson 2.10
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#2065 [eclipse/xtext#2131] update to GSON 2.10.1
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Labels: releng

#2071 update to tycho 3.0.3
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Labels: releng

#2072 FileSourceFolderTest
  org.eclipse.xtext.tests/src/org/eclipse/xtext/workspace/FileSourceFolderTest.java
Labels: bug

#2073 [releng] Bootstrap against 2.30.0.M3
  gradle/versions.gradle
Labels: releng, bot

#2076 [releng] Bootstrap against 2.30.0.RC1
  gradle/versions.gradle
Labels: releng, bot

#2075 [eclipse/xtext#2138] update to gradle 7.6.1
  gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
Labels: releng

#2077 [releng] Bootstrap against 2.30.0.RC2
  gradle/versions.gradle
Labels: releng, bot

#2078 [eclipse/xtext#2136] fix deprecation with gradle 8
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/lsGradleFatjar.ide/build.gradle
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Labels: releng

#2079 [releng] Update Xtext version to 2.31.0
  gradle/versions.gradle
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testing/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
  org.eclipse.xtext.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.util/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
  org.eclipse.xtext/META-INF/MANIFEST.MF
  releng/p2/category.xml
  releng/p2/pom.xml
  releng/pom.xml
  releng/releng-target/pom.xml
Labels: releng, bot

#2080 [releng] Bootstrap against 2.30.0
  gradle/versions.gradle
Labels: releng, bot

#2083 [#2081] update to jetty 9.4.51.v20230217
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.web/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
Labels: releng
